steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/vaidya-hms-dev/hms-repo/hms-web:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://hms-backend-1062509658389.asia-south1.run.app/api'
      - '--build-arg'
      - 'NEXT_PUBLIC_WS_URL=/'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/vaidya-hms-dev/hms-repo/hms-web:latest'
images:
  - 'asia-south1-docker.pkg.dev/vaidya-hms-dev/hms-repo/hms-web:latest'
