export * from './types';
export * from './proformaNarrative';
export { default as ProformaSentenceView } from './ProformaSentenceView';
export { default as ProformaPrintView } from './ProformaPrintView';
export { default as ProformaHeaderSection } from './ProformaHeaderSection';
export { default as ProformaCoupleSection } from './ProformaCoupleSection';
export { default as ProformaFemaleSection } from './ProformaFemaleSection';
export { default as ProformaMaleSection } from './ProformaMaleSection';
export { default as ProformaInvestigationsSection } from './ProformaInvestigationsSection';
export { default as ProformaExamSection } from './ProformaExamSection';
export { default as ProformaPlanSection } from './ProformaPlanSection';
export { default as ProformaSpecialtySections } from './ProformaSpecialtySections';
